# This is a basic workflow to help you get started with Actions

name: Build for Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - name: Get current time (for artifact)
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD

      - uses: actions/upload-artifact@v2
        env:
          DATE: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          name: calculadora-win-$DATE
          path: src/dist/windows
