# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Aplicação Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuração do Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalação de dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Linting com flake8
      run: |
        # para a build se existirem erros de sintaxe Python ou variáveis não definidas
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero trata todos os erros como avisos. O editor do Github tem 127 caracteres
        # de largura
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Testes com pytest
      run: pytest
