# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Calculadora

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # versão da máquina virtual
    runs-on: ubuntu-latest

    # criação de jobs para várias versões de Python
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']

    # define o nome do job consoante a versão do Python
    name: Python ${{ matrix.python-version }}

    # ações a efetuar para cada job
    steps:
    - uses: actions/checkout@v2

    - name: Configuração do Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalação de dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Linting com flake8
      run: |
        # pára a build se existirem erros de sintaxe Python ou variáveis não definidas
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero trata todos os erros como avisos. O editor do Github tem 127 caracteres
        # de largura
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Testes com pytest
      run: pytest
